### ISSUE TITLE
Documentation: Examples in Readme

### ISSUE THREAD

**Issue by mayurankv** [Developer-Mike/calctex#1]
Would be great to have some examples in the Readme! For example, where does the `=` sign go? In the latex or next to it? Does this work for double dollar `$$` math environments? Does it work in editing mode, reading mode or both? I can't seem to get it to work right now unfortunately.

**Comment by mayurankv** [comment]
Also would this work for macros set up via the latex preamble plugin? i.e. setting `\half` to `\frac{1}{2}`, would $\hf+1$ be calculated?

**Comment by Developer-Mike** [comment]
There were many bugs in the first version. I rewrote the parsing algorithm and now it should work with `$$`. I think samples in the README.md are not needed because everything is self-explaining. The `=` sign goes after the expression you want to calculate.

I haven't tried it with macros but I suspect they won't work.
